### ISSUE TITLE
Please add Typescript definition file 

### ISSUE THREAD

**Issue by panuganti** [Initsogar/cordova-webintent#60]
Can you please add a typescript definition file.. and in a way that it's easy to import the relevant class in Angular2 apps ? (I'd like to use this plugin in my Ionic-v2 app with typescript.) 
If you can add documentation for using typescript definition file, that'd be great. Thanks.

**Comment by FdezRomero** [comment]
Have you tried using [Ionic Native](http://ionicframework.com/docs/v2/native)? It seems that they made a nice wrapper for this plugin with TypeScript definitions ;-)

**Comment by panuganti** [comment]
Yes, I have opened similar issue in ionic-native and now, it has. Thanks. I'm closing this issue.
